#! /usr/bin/python

import json
import glob
import re
import os

d = {'j': 'images.json', 'f': 'positive2', 'r': r'(.+)_face_(\d+).jpg'}
# d = {'j': 'non.json', 'f': 'negative', 'r': r'(.+)_non_(\d+).jpg'}

def cmp_endings(x, y):
    mx = re.match(d['r'], x)
    my = re.match(d['r'], y)

    if mx.group(1) == my.group(1):
        return int(mx.group(2)) - int(my.group(2))
    else: 
        if mx.group(1) < my.group(1):
            return -1
        elif mx.group(1) > my.group(1):
            return 1
        else:
            return 0

if __name__ == "__main__":

    img = glob.glob(os.path.join(d['f'], '*.jpg'))
        
    with open(d['j'], 'w') as f:
        json.dump(sorted(img, cmp=cmp_endings), f)
